name: C# Build with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}    
    #runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    - name: Create Build Directory
      run: mkdir -p build
      
    - name: Configure CMake
      run: |
        if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
          cmake -S . -B build -DCMAKE_CSharp_COMPILER=csc
        else
          cmake -S . -B build
        fi
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Restore dependencies
      run: dotnet restore build/Upsilon.Apps.Passkey.Interfaces.sln
      
    - name: Build
      run: dotnet build --no-restore build/Upsilon.Apps.Passkey.Interfaces.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal build/Upsilon.Apps.Passkey.Interfaces.sln

permissions:
  contents: read
  issues: write
  pull-requests: write