name: C# Build with CMake

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    #strategy:
    #  matrix:
    #    os: [ubuntu-latest, windows-latest]
    #
    #runs-on: ${{ matrix.os }}    
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Install CMake
      uses: lukka/get-cmake@latest
      
    - name: Create Build Directory
      run: mkdir -p build
      
    - name: Configure CMake
      run: cmake -S . -B build
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Restore dependencies
      run: dotnet restore build/Upsilon.Apps.Passkey.Core.sln
      
    - name: Build
      run: dotnet build --no-restore build/Upsilon.Apps.Passkey.Core.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal build/Upsilon.Apps.Passkey.Core.sln

permissions:
  contents: read
  issues: write
  pull-requests: write