name: C# Build with CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}    
    #runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore Upsilon.Apps.Passkey.Interfaces.sln
      
    - name: Build
      run: dotnet build Upsilon.Apps.Passkey.Interfaces.sln --no-restore --configuration Release
      

permissions:
  contents: read
  issues: write
  pull-requests: write